name: Main Build/Pack .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -p:RepositoryCommit=${{ github.sha }} -o .out/packages
    - name: Tag the commit
      run: |
        git config --global user.email "no-reply@vaettir.net"
        git config --global user.name "Tagger"
        git tag -a "v${{ steps.version.outputs.version }}" -m "Version ${{ steps.version.outputs.version }}"
        git push --follow-tags
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          .out/packages
      

